plugins {
    id("maven-publish")
}

apply(plugin: "net.fabricmc.fabric-loom-remap")
// apply(plugin: "dev.architectury.loom")
apply(plugin: "com.replaymod.preprocess")
apply(plugin: "me.fallenbreath.yamlang")
apply(plugin: "com.hypherionmc.modutils.modpublisher")

String modPlatform = "fabric"
//boolean fabricLike = modPlatform == "fabric" || modPlatform == "quilt"
//boolean forgeLike = modPlatform == "forge" || modPlatform == "neoforge"
int mcVersion = 0

preprocess {
    mcVersion = vars.get().get("MC")
    vars.put("MC", mcVersion)
    //vars.put("FORGE", modPlatform == "forge" ? 1 : 0)
    //vars.put("NEO_FORGE", modPlatform == "neoforge" ? 1 : 0)
    //vars.put("FABRIC_LIKE", fabricLike ? 1 : 0)
    //vars.put("FORGE_LIKE", forgeLike ? 1 : 0)
}

JavaVersion javaCompatibility
if (mcVersion >= 12005) {
    javaCompatibility = JavaVersion.VERSION_21
} else if (mcVersion >= 11800) {
    javaCompatibility = JavaVersion.VERSION_17
} else if (mcVersion >= 11700) {
    javaCompatibility = JavaVersion.VERSION_16
} else {
    javaCompatibility = JavaVersion.VERSION_1_8
}

boolean jitpack = System.getenv("JITPACK") == "true"
boolean releasing = System.getenv("BUILD_RELEASE") == "true"
boolean ci = jitpack || releasing

repositories {
    mavenLocal()

    maven {
        name = "NeoForge"
        url = "https://maven.neoforged.net/releases/"
    }

    maven {
        name = "Curse Maven"
        url = "https://www.cursemaven.com"
    }

    maven {
        name = "Modrinth Maven"
        url = "https://api.modrinth.com/maven"
    }

    maven {
        name = "Jitpack Maven"
        url = "https://www.jitpack.io"
    }

    maven {
        name = "Nyan Maven"
        url = "https://maven.hendrixshen.top/releases"
    }

    mavenCentral()
}

dependencies {
    // Development environment
    minecraft("com.mojang:minecraft:${project.property("dependencies.minecraft_version")}")
    mappings(loom.layered {officialMojangMappings()})

    // Annotation processor
    modCompileOnly("org.projectlombok:lombok:${project.property("dependencies.lombok_version")}")
    annotationProcessor("org.projectlombok:lombok:${project.property("dependencies.lombok_version")}")

    // Dependency
    modApi(annotationProcessor("top.hendrixshen.magiclib:magiclib-all-${project.name}:${project.property("dependencies.magiclib_version")}"))

    //switch (modPlatform) {
    //    case "fabric":
    //        break
    //    case "forge":
    //        forge("net.minecraftforge:forge:${project.property("dependencies.minecraft_version")}-${project.property("dependencies.forge_version")}")
    //        break
    //    case "neoforge":
    //        neoForge("net.neoforged:neoforge:${project.property("dependencies.neoforge_version")}")
    //        break
    //}
}

loom {
    //silentMojangMappingsLicense()

    // accessWidenerPath.set(file("src/main/resources/${project.parent.property("mod.id")}.accesswidener"))

    //if (modPlatform == "forge") {
    //    forge {
    //        convertAccessWideners.set(true)
    //        mixinConfig("${project.parent.property("mod.id")}.mixins.json")
    //    }
    //}

    mixin.useLegacyMixinAp = true

    runConfigs.configureEach {
        // Dump modified classes automatically.
        property("mixin.debug.export", "true")
    }

    runConfigs.named("client") {
        programArgs([
                "--width",
                project.getOrDefault("ow.game.window.width", "1920"),
                "--height",
                project.getOrDefault("ow.game.window.height", "1080"),
                "--username",
                project.getOrDefault("ow.game.window.username", "dev")
        ])
        vmArgs("-Dmagiclib.debug=true")
        vmArgs("-Dmagiclib.dev.qol=true")
        vmArgs("-Dmagiclib.dev.qol.dfu.destroy=true")
        runDir("run/client")
        ideConfigGenerated(true)
    }

    runConfigs.named("server") {
        vmArgs("-Dmagiclib.debug=true")
        vmArgs("-Dmagiclib.dev.qol=true")
        vmArgs("-Dmagiclib.dev.qol.dfu.destroy=true")
        runDir("run/server")
    }

    //if (fabricLike) {
        runs {
            mixinAuditClient {
                inherit(client)
                vmArgs("-Dmagiclib.debug.mixinAuditor.enable=true")
                ideConfigGenerated(false)
                runDir("run/client")
            }

            mixinAuditServer {
                inherit(server)
                vmArgs("-Dmagiclib.debug.mixinAuditor.enable=true")
                ideConfigGenerated(false)
                runDir("run/server")
            }
        }
    //}

    // Setup client default settings.
    runClient {
        defaultCharacterEncoding = "UTF-8"

        doFirst {
            file("run/client/config").mkdirs()
            file("run/client/options.txt").with { File f ->
                {
                    if (!f.exists()) {
                        f.parentFile.mkdirs()
                        f.withWriter { BufferedWriter writer ->
                            writer.writeLine("autoJump:false")
                            writer.writeLine("enableVsync:false")
                            writer.writeLine("forceUnicodeFont:true")
                            writer.writeLine("fov:1.0")
                            writer.writeLine("gamma:16.0")
                            writer.writeLine("guiScale:3")
                            writer.writeLine("lang:${Locale.getDefault().toString().toLowerCase()}")
                            writer.writeLine("maxFps:260")
                            writer.writeLine("renderDistance:10")
                            writer.writeLine("soundCategory_master:0.0")
                        }
                    }
                }
            }
        }
    }

    // Setup server default settings.
    runServer {
        defaultCharacterEncoding = "UTF-8"

        doFirst {
            // Agree eula before server init.
            file("run/server/eula.txt").with { File f ->
                {
                    if (!f.exists()) {
                        f.parentFile.mkdirs()
                        f.withWriter { BufferedWriter writer ->
                            writer.writeLine("#By changing the setting below to TRUE you are indicating your agreement to our EULA (https://account.mojang.com/documents/minecraft_eula).")
                            writer.writeLine("#${new Date()}")
                            writer.writeLine("eula=true")
                        }
                    }
                }
            }
        }
    }
}

var modVersion = property("mod.version").toString()

var archivesBaseName = property("mod.archives_base_name").toString()
var modVersionSuffix = ""
var artifactVersion = modVersion
var artifactVersionSuffix = ""
// detect github action environment variables
// https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables
if (!releasing) {
    modVersionSuffix += "-SNAPSHOT"
    artifactVersionSuffix = "-SNAPSHOT"  // A non-release artifact is always a SNAPSHOT artifact
}
var fullModVersion = modVersion + modVersionSuffix
var fullProjectVersion
var fullArtifactVersion

// Example version values:
//   project.mod_version     1.0.3                      (the base mod version)
//   modVersionSuffix        +build.88                  (use github action build number if possible)
//   artifactVersionSuffix   -SNAPSHOT
//   fullModVersion          1.0.3+build.88             (the actual mod version to use in the mod)
//   fullProjectVersion      v1.0.3-mc1.15.2+build.88   (in build output jar name)
//   fullArtifactVersion     1.0.3-mc1.15.2-SNAPSHOT    (maven artifact version)

if (jitpack) {
    // move mc version into archivesBaseName, so jitpack will be able to organize archives from multiple subprojects correctly
    base.archivesName = "${archivesBaseName}-mc${project.name}"
    fullProjectVersion = "v${modVersion}${modVersionSuffix}"
    fullArtifactVersion = artifactVersion + artifactVersionSuffix
} else {
    base.archivesName = archivesBaseName
    fullProjectVersion = "v${modVersion}-mc${project.name}${modVersionSuffix}"
    fullArtifactVersion = "${modVersion}-mc${project.name}${artifactVersionSuffix}"
}
version = fullProjectVersion

sourceSets {
    dummy {
        compileClasspath += main.compileClasspath
        runtimeClasspath += main.runtimeClasspath
    }

    main.compileClasspath += dummy.output
}

java {
    sourceCompatibility = javaCompatibility
    targetCompatibility = javaCompatibility

    withSourcesJar()
}

remapJar {
    //if (forgeLike) {
    //    if (modPlatform == "neoforge") {
    //        atAccessWideners.add("${project.parent.property("mod.id")}.accesswidener")
    //    }
    //
    //    exclude("${project.parent.property("mod.id")}.accesswidener")
    //}
}

processResources {
    outputs.upToDateWhen { false }

    [
            "fabric.mod.json"            : ["fabric"],
            "META-INF"                   : ["forge", "neoforge"],
            "META-INF/mods.toml"         : ["forge", "neoforge", mcVersion < 12005 ? "neoforge": "none"],
            "META-INF/neoforge.mods.toml": [mcVersion > 12004 ? "neoforge" : "none"]
    ].forEach { file, platforms ->
        if (platforms.contains(modPlatform)) {
            filesMatching(file) {
                expand([
                        "magiclib_dependency" : project.property("dependencies.magiclib_dependency"),
                        "minecraft_dependency": project.property("dependencies.minecraft_dependency"),
                        "mod_alias"           : project.parent.property("mod.id"),
                        "mod_description"     : project.parent.property("mod.description"),
                        "mod_homepage"        : project.parent.property("mod.homepage"),
                        "mod_id"              : project.parent.property("mod.id"),
                        "mod_license"         : project.parent.property("mod.license"),
                        "mod_name"            : project.parent.property("mod.name"),
                        "mod_sources"         : project.parent.property("mod.sources"),
                        "mod_version"         : fullModVersion
                ])
            }
        } else {
            exclude(file)
        }
    }

    filesMatching("${project.parent.property("mod.id")}.mixins.json") {
        expand([
                "MIXIN_COMPATIBILITY_LEVEL": "JAVA_${javaCompatibility.majorVersion}"
        ])
    }

    from("${rootDir}/LICENSE")
    from("${rootDir}/icon.png") {
        //if (fabricLike) {
            into("assets/${project.parent.property("mod.id")}")
        //}
    }
}

yamlang {
    targetSourceSets.set([sourceSets.main])
    inputDir.set("assets/${project.parent.property("mod.id")}/lang")
}

tasks.withType(PublishToMavenRepository).configureEach {
    Provider<Boolean> predicate = provider {
        repository == publishing.repositories.mavenLocal ||
                (repository == publishing.repositories.projectLocalSnapshot && publication == publishing.publications.snapshot) ||
                (repository == publishing.repositories.projectLocalRelease && publication == publishing.publications.release)
    }

    onlyIf {
        predicate.get()
    }
}

tasks.withType(JavaCompile).configureEach { JavaCompile task ->
    task.options.encoding = "UTF-8"
}

tasks.register("cleanRuns", DefaultTask.class) {
    doLast {
        file(loom.runConfigs.client.runDir).parentFile.deleteDir()
    }
}

tasks.register("cleanRunClient", DefaultTask.class) {
    doLast {
        file(loom.runConfigs.client.runDir).deleteDir()
    }
}

tasks.register("cleanRunServer", DefaultTask.class) {
    doLast {
        file(loom.runConfigs.server.runDir).deleteDir()
    }
}

[
        "cleanRuns", "cleanRunClient", "cleanRunServer",
        "runClient", "runServer",
        "runMixinAuditClient", "runMixinAuditServer",
        "preprocessCode", "preprocessResources",
        "preprocessTestCode", "preprocessTestResources"
].forEach { taskName ->
    if (tasks.getNames().contains(taskName)) {
        tasks.named(taskName) {
            it.group = "${project.property("mod.id")}"
        }
    }
}

var minecraftVersions = property("game_versions").toString().split("\n")

// https://github.com/firstdarkdev/modpublisher
publisher {

    apiKeys {
        github(System.getenv("GITHUB_TOKEN") ?: "unset")
    }

    // debug = true

    versionType = property("mod.version.type").toString()
    projectVersion = fullProjectVersion

    gameVersions = minecraftVersions
    loaders = ["fabric"]

    artifact.set(tasks.remapJar)

    github {
        repo(System.getenv("REPO"))
        tag(System.getenv("TAG"))
    }

}
