import groovy.json.JsonSlurper

pluginManagement {
    repositories {
        mavenLocal()
        mavenCentral()
        gradlePluginPortal()

        maven {
            name = "FabricMC"
            url = "https://maven.fabricmc.net"
        }

        maven {
            name = "Architectury"
            url = "https://maven.architectury.dev"
        }

        maven {
            name = "MinecraftForge"
            url = "https://files.minecraftforge.net/maven"
        }

        maven {
            name = "NeoForge"
            url = "https://maven.neoforged.net/releases"
        }

        maven {
            name = "Jitpack"
            url = "https://jitpack.io"
        }

        maven {
            url = "https://maven.firstdark.dev/releases"
        }
    }

    resolutionStrategy {
        eachPlugin {
            switch (requested.id.id) {
                case "com.replaymod.preprocess": {
                    useModule("com.github.Fallen-Breath:preprocessor:${requested.version}")
                    break
                }
            }
        }
    }
}

Map<String, Map<String, Boolean>> settings = file("settings.json").withReader {
    new JsonSlurper().parse(it) as Map<String, Map<String, Boolean>>
}

for (Map.Entry<String, Boolean> version : settings.get("versions").entrySet()) {
    include(":${version.key}")
    ProjectDescriptor proj = project(":${version.key}")
    proj.setProjectDir(file("versions/${version.key}"))
    proj.setBuildFileName(version.value ? "../../common.gradle" : "../../common.remap.gradle")
}
